config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :tasks
  resources :users, only: [:new, :create, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :task_name, presence: true, length: { maximum: 15 }
  validates :task_detail, presence: true, length: { maximum: 255 }
  validates :status, presence: true
  validates :priority, presence: true
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  # 自動的に推論指定いるので、source:と書く必要はない

  enum status: {
    not_started_yet: 0,
    under_start: 1,
    completion: 2
    }
  enum priority: {
    high: 0,
    medium: 1,
    low: 2
    }

    # scope :creation_date_descending, -> {order(created_at: :desc)}
    # scope :end_deadline_descending, -> {order(expired_at: :desc)}
    # scope :highest_priority, -> {order(priority: :asc)}
    scope :search_task_name, -> (params) { where('task_name LIKE ?', "%#{params}%")}
    scope :search_status, -> (params) { where(status: "#{params}")}
    scope :search_label, -> (params) { where(labels: {id: "#{params}"})}
    # scope :search_label_two, -> (params) { where(label_id: "#{params}")}
    scope :search_labels, -> (params) {
      task_ids = Labelling.where(label_id: params).pluck(:task_id)
      where(id: task_ids)
    }
    # def self.search_label_two(params)
    #   where(id: Labelling.where(label_id: "#{params}").pluck(:task_id))
    # end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @tasks = current_user.tasks.includes(:labels).order(created_at: :desc)
    @tasks = @tasks.reorder(expired_at: :desc) if params[:sort_expired]
    @tasks = @tasks.reorder(priority: :asc) if params[:sort_priority]
    @tasks = @tasks.search_task_name(params[:search]) if params[:search].present?
    @tasks = @tasks.search_status(params[:status]) if params[:status].present?
    @tasks = @tasks.search_labels(params[:label_id]) if params[:label_id].present?

    @tasks = @tasks.page(params[:page]).per(5)
    # @tasks = current_user.tasks.includes([:labels]).creation_date_descending.page(params[:page]).per(5)
    # @tasks = current_user.tasks.includes([:labels]).end_deadline_descending.page(params[:page]).per(5) if params[:sort_expired] 
    # @tasks = current_user.tasks.includes([:labels]).highest_priority.page(params[:page]).per(5) if params[:sort_priority]
    # if params[:task].present?
    #   if params[:task][:search].present? && params[:task][:status].present? && params[:task][:label_id].present? # タスク名、ステータス、ラベル検索
    #     @tasks = current_user.tasks.search_task_name(params[:task][:search]).search_status(params[:task][:status]).joins(:labels).search_label(params[:task][:label_id]).includes([:labels]).includes([:labellings]).page(params[:page]).per(5)
    #   elsif params[:task][:search].present? && params[:task][:status].present? # タスク名、ステータス検索
    #     @tasks = current_user.tasks.search_task_name(params[:task][:search]).search_status(params[:task][:status]).includes([:labels]).page(params[:page]).per(5)
    #   elsif params[:task][:search].present? && params[:task][:label_id].present? # タスク名、ラベル検索
    #     @tasks = current_user.tasks.search_task_name(params[:task][:search]).joins(:labels).search_label(params[:task][:label_id]).includes([:labels]).includes([:labellings]).page(params[:page]).per(5)
    #   elsif params[:task][:status].present? && params[:task][:label_id].present? # ステータス、ラベル検索
    #     @tasks = current_user.tasks.search_status(params[:task][:status]).joins(:labels).search_label(params[:task][:label_id]).includes([:labels]).includes([:labellings]).page(params[:page]).per(5)
    #   elsif params[:task][:search].present? # タスク名検索
    #     @tasks = current_user.tasks.search_task_name(params[:task][:search]).includes([:labels]).page(params[:page]).per(5)
    #   elsif params[:task][:status].present? # ステータス検索
    #     @tasks = current_user.tasks.search_status(params[:task][:status]).includes([:labels]).page(params[:page]).per(5)
    #   elsif params[:task][:label_id].present? # ラベル検索
    #     @tasks =  Task.search_label_two(params[:task][:label_id]).includes([:labels]).includes([:user]).page(params[:page]).per(5)
        # @tasks =  Task.where(id: Labelling.where(label_id: (params[:task][:label_id])).pluck(:task_id)).page(params[:page]).per(5)
        # @tasks = current_user.tasks.joins(:labels).search_label(params[:task][:label_id]).page(params[:page]).per(5)
    #   end
    # end
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: t('notice.Task was successfully created')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    unless params[:task][:label_ids]
      @task.labellings.destroy_all
    end
    if @task.update(task_params)
      redirect_to tasks_path, notice: t('notice.Task was successfully updated')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: t('notice.Task was successfully destroyed')
  end

  private
  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:task_name, :task_detail, :expired_at, :status, :priority, :user_id, { label_ids: [] })
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_eeplanation">
      <h2><%= @task.errors.count %><%= t('view.error') %> <%= t('view.prohibited this task from being saved') %></h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task_name">
    <%= form.label :task_name %>
    <%= form.text_field :task_name, class: 'form-control' %>
  </div>
  <br>

  <% current_user.labels.each do |label| %>
    <% if action_name == 'new' %>
      <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
      <%= label.label_name %>
    <% elsif action_name == 'edit' %>
      <%= form.check_box :label_ids, { multiple: true, checked: @task.label_ids.include?(label.id), disabled: label[:disabled], include_hidden: false }, label[:id] %>
      <%= label.label_name %>
    <% end %>
  <% end %>
  
  <div class="task_detail">
    <%= form.label :task_detail %>
    <%= form.text_area :task_detail, class: 'form-control' %>
  </div>
  <div class="expired_at">
    <%= form.label :expired_at %>
    <%= form.datetime_field :expired_at, class: 'form-control' %>
  </div>
  <br>
  <div class="status">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses_i18n.keys.map{|k| [I18n.t("enums.task.status.#{k}"), k]} %>
  </div>
  <br>
  <div class="priority">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities_i18n.keys.map{|k| [I18n.t("enums.task.priority.#{k}"), k]} %>
  </div>
  <br>
  <%= form.submit class: 'bun btn-primary'%>
<% end %>

app/views/tasks/edit.html.erb
<h2><%= t('view.Edit task') %></h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1><%= t('view.Tasks index') %></h1>

<%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <%= form.label :search, t('view.Task name search') %>
  <%= form.text_field :search %>
  <%= form.label :status, t('view.Status search') %>
  <%= form.select :status, Task.statuses_i18n.keys.map{|k| [I18n.t("enums.task.status.#{k}"), k]}, {include_blank: true} %>
  <%= form.label :label_id, t('view.Label search') %>
  <%= form.select :label_id, current_user.labels.collect { |label| [ label.label_name, label.id ] }, include_blank: true %>
  <%# 基本的にレイアウトを崩してしまうモノ（この場合はラベル）は、詳細画面にのみ表示されるようにしましょう %>
  <%= form.submit t('view.Search') %>
<% end %>
<br>
<%= link_to t('view.Create a new task'), new_task_path, class: 'btn btn-primary' %>
<%= link_to t('view.Create a new label'), new_label_path, class: 'btn btn-success' %>
<br><br>
<table>
  <tr>
    <th><%= t('view.Task name') %></th>
    <th><%= t('view.Label name') %></th>
    <th><%= t('view.Task detail') %></th>
    <th><%= link_to t('view.expired_at'), tasks_path(sort_expired: "true") %></th>
    <th><%= t('view.status') %></th>
    <th><%= link_to t('view.priority'), tasks_path(sort_priority: "true") %></th>
    <th><%= t('view.Task creator') %></th>
  </tr>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.task_name %></td>
      <td>
        <% task.labels.each do |label| %>
          <%= label.label_name %>
        <% end %>
      </td>
      <td><%= task.task_detail %></td>
      <td><%= l task.expired_at, format: :long %></td>
      <td><%= task.status_i18n %></td>
      <td><%= task.priority_i18n %></td>
      <td><%= task.user.user_name %></td>
      <td><%= link_to t('view.Show'), task_path(task.id), class: 'btn btn-primary' %></td>
      <td><%= link_to t('view.Edit'), edit_task_path(task.id), class: 'btn btn-success' %></td>
      <td><%= link_to t('view.Delete'), task_path(task.id), method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h2><%= t('view.Create a task') %></h2>
<%= render 'form' %>

app/views/tasks/show.html.erb
<table>
  <tr>
    <th><%= t('view.Task name') %>:</th>
    <td><%= @task.task_name %></td>
  </tr>
  <tr>
    <th><%= t('view.Label name') %>:</th>
    <td>
      <% @task.labels.each do |label| %>
        <%= label.label_name %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th><%= t('view.Task detail') %>:</th>
    <td><%= @task.task_detail %></td>
  </tr>
  <tr>
    <th><%= t('view.expired_at') %>:</th>
    <td><%= l @task.expired_at, format: :long %></td>
  </tr>
  <tr>
    <th><%= t('view.status') %>:</th>
    <td><%= @task.status_i18n %></td>
  </tr>
  <tr>
    <th><%= t('view.priority') %>:</th>
    <td><%= @task.priority_i18n %></td>
  </tr>
</table>
<br>
<%= link_to t('view.Return to task list screen'), tasks_path %>