config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :tasks
  resources :users, only: [:new, :create, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/label.rb
class Label < ApplicationRecord
  validates :label_name, presence: true
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
  belongs_to :user
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  # GET /labels or /labels.json
  def index
    @labels = current_user.labels
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = current_user.labels.new(label_params)
    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: t('notice.Label was successfully created') }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: t('notice.Label was successfully updated') }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: t('notice.Label was successfully destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = current_user.labels.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:label_name)
    end
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= label.errors.count %><%= t('view.error') %> <%= t('view.prohibited this label from being saved') %></h2>
 
      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label_name %>
    <%= form.text_field :label_name, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1><%= t('view.Label edit screen') %></h1>

<%= render 'form', label: @label %>

<%= link_to t('view.To label show screen'), @label %> |
<%= link_to t('view.To label list screen'), labels_path %>

app/views/labels/index.html.erb
<h1><%= t('view.Label list screen') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('view.Label name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.label_name %></td>
        <td><%= link_to t('view.Show'), label, class: 'btn btn-primary' %></td>
        <td><%= link_to t('view.Edit'), edit_label_path(label), class: 'btn btn-success' %></td>
        <td><%= link_to t('view.Delete'), label, method: :delete, class: 'btn btn-danger', data: { confirm: t('view.Are you sure you want to delete it?') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('view.Create a new label'), new_label_path %>

app/views/labels/new.html.erb
<h1><%= t('view.New label registration') %></h1>

<%= render 'form', label: @label %>
<br>
<%= link_to t('view.To label list screen'), labels_path %>

app/views/labels/show.html.erb
<p>
  <strong><%= t('view.Label name') %>:</strong>
  <%= @label.label_name %>
</p>

<%= link_to t('view.To label edit screen'), edit_label_path(@label) %> |
<%= link_to t('view.To label list screen'), labels_path %>