config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :tasks
  resources :users, only: [:new, :create, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  before_destroy :one_administrator_required
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  # after_update :admin_update_exist
  before_update :admin_update_exist

  private
  def one_administrator_required
    errors.add :admin
    throw(:abort) if User.where(admin: true).length == 1 && self.admin?
  end

  def admin_update_exist
    errors.add :admin
    if User.where(admin: true).length == 1
      if User.where(admin: true).first.id == self.id
        if self.admin? == false
          throw(:abort)
        end
      end
    end
  end
  # def admin_update_exist
  #   errors.add :admin
  #   if User.where(admin: true).length == 0
  #     raise ActiveRecord::Rollback
  #   end
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: %i[ new create ]
  before_action :set_user, only: %i[ edit update show destroy ]
  before_action :require_admin

  def index
    @users = User.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id), notice: t('notice.User was successfully created', name: @user.user_name)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: t('notice.User was successfully updated', name: @user.user_name)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: t('notice.User was successfully destroyed', name: @user.user_name )
    else
      @users = User.includes(:tasks)
      render :index
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to tasks_path, notice: t('notice.Only the administrator can access it') unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[ new create ]
  before_action :set_user, only: %i[ show destroy ]
  before_action :back_when_logged_in, only: %i[ new create ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: t('notice.User was successfully created', name: @user.user_name)
    else
      render :new
    end
  end

  def show
    redirect_to tasks_path unless @user.id == current_user.id
  end


  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :admin, :password,:password_confirmation)
  end

  def back_when_logged_in
    redirect_to tasks_path if logged_in?
  end
end

app/views/admin/users/_form.html.erb
<%= form_with( model: [:admin, @user], local:true ) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explantion">
      <h2><%= @user.errors.count %><%= t('view.error') %><%= @user.user_name %><%= t('view.prohibited this user from being saved') %></h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_name">
    <%= f.label :user_name %>
    <%= f.text_field :user_name, class: 'form-control' %>
  </div>
  <div class="user_email">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <br>
  <div class="admin">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>
  <div class="user_password">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="user_confirmation">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <br>
  <%= f.submit t('view.Create my account') %>
<% end %>
<br>
<%= link_to t('view.To login screen'), new_session_path %>

app/views/admin/users/edit.html.erb
<h2><%= t('view.User edit') %></h2>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1><%= t('view.User list') %></h1>

<%= link_to t('view.New user registration'), new_admin_user_path, class: 'btn btn-primary' %>

<% if @user.present? %>
<div id="error_explantion">
  <h2><%= @user.errors.count %><%= t('view.error') %><%= @user.user_name %><%= t('view.prohibited this user from being saved') %></h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<br><br>
<table>
  <tr>
    <th><%= t('view.User name') %></th>
    <th><%= t('view.Number of user tasks') %></th>
    <th><%= t('view.Administrator') %></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.user_name %></td>
      <td><%= user.tasks.length %></td>
      <td><%= user.admin %></td>
      <td><%= link_to t('view.Show'), admin_user_path(user.id), class: 'btn btn-primary' %></td>
      <td><%= link_to t('view.Edit'), edit_admin_user_path(user.id), class: 'btn btn-success' %></td>
      <td><%= link_to t('view.Delete'), admin_user_path(user.id), method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>
<br><br>
<%= link_to t('view.Return to task list screen'), tasks_path %>

app/views/admin/users/new.html.erb
<h2><%= t('view.Sign up') %></h2>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h2><%= t('view.page of', name: @user.user_name) %></h2>
<p><%= t('view.email', email: @user.email) %></p>

<table>
  <tr>
    <th><%= t('view.Task name') %></th>
    <th><%= t('view.Task detail') %></th>
    <th><%= t('view.Task creator') %></th>
    <th><%= t('view.admin') %></th>
  </tr>
  <% @user.tasks.each do |user_task| %>
    <tr>
      <td><%= user_task.task_name %></td>
      <td><%= user_task.task_detail %></td>
      <td><%= user_task.user.user_name %></td>
      <td><%= user_task.user.admin %></td>
    </tr>
  <% end %>
</table>

<%= link_to t('view.Return to task list screen'), tasks_path %>