config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :tasks
  resources :users, only: [:new, :create, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
      <ul>
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <li><%= link_to t('view.Create a new task'), new_task_path %></li>
        <li><%= link_to t('view.Create a new label'), new_label_path %><li>
        <li><%= link_to t('view.Return to task list screen'), tasks_path %></li>
        <% if current_user.admin? %>
          <li><%= link_to t('view.To user list screen'), admin_users_path %></li>
        <% end %>
      </ul>
      <% else %>
      <ul>
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "Login", new_session_path %></li>
      </ul>
      <% end %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    </header>
      <main>
        <%= yield %>
      </main>
    <footer>
      <p><%= t('view.Task management will increase your work productivity') %></p>
    </footer>
  </body>
</html>